
#' Plot gene tracks
#' 
#' Plot gene annotation tracks from `ensembldb` data.
#' 
#' @details This function is called by plot.locus(). It can used to plot the 
#' gene annotation tracks on their own. It uses base graphics, so layout() can 
#' be used to position adjacent plots above or below.
#' @param locus Object of class 'locus' generated by [locus()].
#' @param filter_gene_name Vector of gene names to display.
#' @param filter_gene_biotype Vector of gene biotypes to be filtered. Use
#' [ensembldb::listGenebiotypes()] to display possible biotypes. For example, 
#' `ensembldb::listGenebiotypes(EnsDb.Hsapiens.v75)`
#' @param cex.axis Specifies font size for axis numbering.
#' @param cex.text Font size for gene text.
#' @param maxrows Specifies maximum number of rows to display in gene 
#' annotation panel.
#' @param xticks Logical whether x axis ticks and numbers are plotted.
#' @param xlab Title for x axis. Defaults to chromosome `seqname` specified 
#' in `locus`.
#' @param border Logical whether a bounding box is plotted.
#' @param gene_col Colour for gene lines.
#' @param exon_col Fill colour for exons.
#' @param exon_border Border line colour outlining exons. Set to `NA` for no 
#' border.
#' @param text_pos Character value of either 'top' or 'left' specifying 
#' placement of gene name labels.
#' @return No return value.
#' @examples
#' library(EnsDb.Hsapiens.v75)
#' data(SLE_gwas_sub)
#' loc <- locus(SLE_gwas_sub, gene = 'UBE2L3', flank = 1e5, LD = FALSE)
#' genetracks(loc)
#' 
#' ## Limit the number of tracks
#' genetracks(loc, maxrows = 4)
#' 
#' ## Filter by gene biotype
#' genetracks(loc, filter_gene_biotype = 'protein_coding')
#' 
#' ## Customise colours
#' genetracks(loc, gene_col = 'grey', exon_col = 'orange',
#'            exon_border = 'darkgrey')
#' 
#' @import EnsDb.Hsapiens.v75
#' @importFrom BiocGenerics start end
#' @importFrom graphics axTicks axis lines rect text plot.new
#' @export

genetracks <- function(locus,
                       filter_gene_name = NULL,
                       filter_gene_biotype = NULL,
                       border = FALSE,
                       cex.axis = 0.8,
                       cex.text = 0.7,
                       gene_col = 'blue4',
                       exon_col = 'blue4',
                       exon_border = 'blue4',
                       maxrows = NULL,
                       text_pos = 'top',
                       xticks = TRUE,
                       xlab = NULL,
                       align = TRUE) {
  if (!inherits(locus, "locus")) stop("Object of class 'locus' required")
  TX <- locus$TX
  EX <- locus$EX
  xrange <- locus$xrange
  if (!is.null(filter_gene_name)) {
    TX <- TX[TX$gene_name %in% filter_gene_name, ]
  }
  if (!is.null(filter_gene_biotype)) {
    TX <- TX[TX$gene_biotype %in% filter_gene_biotype, ]
  }
  if (nrow(TX) == 0) {
    message('No genes to plot')
    return(plot.new())
  }
  TX <- mapRow(TX, xlim = xrange, cex.text = cex.text, text_pos = text_pos)
  maxrows <- if (is.null(maxrows)) max(TX$row) else min(c(max(TX$row), maxrows))
  TX <- TX[TX$row <= maxrows, ]
  if (is.null(xlab)) xlab <- paste("Chromosome", locus$seqname, "(Mb)")
  
  if (align) {
    op <- par(tcl = -0.25, las = 1, font.main = 1,
              mgp = c(1.6, 0.3, 0), 
              mar = c(ifelse(xticks, 4, 2), 4, 0.25, 1.5))
    on.exit(par(op))
  }
  
  plot(NA, xlim = xrange,
       ylim = c(-maxrows - 0.3, -0.3), 
       bty = if (border) 'o' else 'n',
       yaxt = 'n', xaxt = 'n',
       xlab = if (xticks) xlab else "",
       ylab = "")
  if (xticks) {
    xd <- diff(xrange) * 0.04
    axis(1, at = xrange + c(-xd, xd), labels = FALSE, lwd.ticks = 0)
    axis(1, at = axTicks(1), labels = axTicks(1) / 1e6, cex.axis = cex.axis,
         lwd = 0, lwd.ticks = 1)
  }
  exheight <- switch(text_pos, "top" = 0.15, "left" = 0.3)
  for (i in seq_len(nrow(TX))) {
    lines(TX[i, c('start', 'end')], rep(-TX[i, 'row'], 2),
          col = gene_col, lwd = 1, lend = 1)
    e <- EX[EX$gene_id == TX$gene_id[i], ]
    exstart <- start(e)
    exend <- end(e)
    rect(exstart, -TX[i, 'row'] - exheight, exend, -TX[i, 'row'] + exheight,
         col = exon_col, border = exon_border, lwd = 0.5, lend = 2, ljoin = 1)
  }
  if (text_pos == "top") {
    tfilter <- which(TX$tmin > (xrange[1] - diff(xrange) * 0.04) & 
                       (TX$tmax < xrange[2] + diff(xrange) * 0.04))
    for (i in tfilter) {
      text(TX$mean[i], -TX[i, 'row'] + 0.45,
           labels = if (TX$strand[i] == "+") {
             bquote(.(TX$gene_name[i]) * symbol("\256"))
           } else {     
             bquote(symbol("\254") * .(TX$gene_name[i]))
           }, cex = cex.text, xpd = NA)
    }
  } else if (text_pos == "left") {
    tfilter <- if (border) {
      which(TX$tmin > xrange[1])
    } else seq_len(nrow(TX))
    for (i in tfilter) {
      text(max(c(TX$start[i], xrange[1] - diff(xrange) * 0.04)), -TX[i, 'row'],
           labels = if (TX$strand[i] == "+") {
             bquote(.(TX$gene_name[i]) * symbol("\256"))
           } else {     
             bquote(symbol("\254") * .(TX$gene_name[i]))
           }, cex = cex.text, pos = 2, xpd = NA)
    }
  }
  
}


# map genes into rows without overlap
mapRow <- function(TX, gap = diff(xlim) * 0.02, cex.text = 0.7, 
                   xlim = range(TX[, c('start', 'end')]),
                   text_pos = 'top') {
  gw <- strwidth(paste0("--", TX$gene_name), units = "inch", 
                 cex = cex.text) * diff(xlim) / par("pin")[1]
  TX$mean <- rowMeans(TX[, c('start', 'end')])
  if (text_pos == 'top') {
    TX$tmin <- TX$mean - gw / 2
    TX$tmax <- TX$mean + gw / 2
  } else if (text_pos == 'left') {
    TX$tmin <- TX$start - gw - gap
    TX$tmax <- TX$end
  }
  TX$min <- apply(TX[, c('start', 'end', 'tmin')], 1, min) - gap / 2
  TX$max <- apply(TX[, c('start', 'end', 'tmax')], 1, max) + gap / 2
  TX$row <- 0
  j <- 1
  while (any(TX$row == 0)) {
    xset <- which(TX$row == 0)
    for (i in xset) {
      # overlap detection
      if (!any(TX$min[i] < TX$max[TX$row == j] &
               TX$max[i] > TX$min[TX$row == j])) {
        TX$row[i] <- j
      }
    }
    j <- j + 1
  }
  TX
}
